#!/bin/bash

#3: Add RSA 4096 bit SSH keys <TBD>
#Tip: try using one generated by JuiceSSH

#Step 1: download keys [from somewhere, maybe NAS, or JuiceSSH, Dropbox, Google Drive, secured USB drive (!!!)...]
#Step 2: integrate keys to make them work.
